/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examenii_p2_victorromero;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Hogar
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        LlenarArbol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupInicial = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Pop_Deportes = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        Pop_Torneos = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtree_Torneos = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();

        jPopupInicial.setComponentPopupMenu(jPopupInicial);

        jMenuItem1.setText("Crear Deporte");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupInicial.add(jMenuItem1);

        jMenuItem4.setText("Añadir Torneo");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Pop_Deportes.add(jMenuItem4);

        jMenuItem2.setText("Listar Equipos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Pop_Torneos.add(jMenuItem2);

        jMenuItem3.setText("Tabla de Clasificacion");
        Pop_Torneos.add(jMenuItem3);

        jMenuItem5.setText("Simulacion");
        Pop_Torneos.add(jMenuItem5);

        jMenuItem6.setText("Agregar Equipos");
        Pop_Torneos.add(jMenuItem6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examenii_p2_victorromero/Images/logo-unitec-color2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 130));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("TORNEOS");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q4");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Q5");
        treeNode1.add(treeNode2);
        jtree_Torneos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_Torneos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtree_Torneos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_TorneosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtree_Torneos);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 770, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtree_TorneosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_TorneosMouseClicked
//        if (SwingUtilities.isRightMouseButton(evt)) {
//            jPopupMenu1.show(jtree_Torneos, evt.getX(), evt.getY());
//        } else {
//            if (evt.isMetaDown()) {
//                System.out.println("pero1");
//                int row = jtree_Torneos.getClosestRowForLocation(evt.getX(), evt.getY());
//                jtree_Torneos.setSelectionRow(row);
//                Object v1 = jtree_Torneos.getSelectionPath().getLastPathComponent();
//                Torneos torneoSelecc = new Torneos();
//                DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) v1;
//                if (nodo.getUserObject().toString().equals("Q1")) {
//                    Pop_Torneos.show(evt.getComponent(), evt.getX(), evt.getY());
//                    deportes.add(crearDeporte());
//                }
//                if (nodo.getUserObject().toString().equals("Q2")) {
//                    Pop_Torneos.show(evt.getComponent(), evt.getX(), evt.getY());
//                    deportes.add(crearDeporte());
//                }
//                if (nodo.getUserObject().toString().equals("Q4")) {
//                    Pop_Torneos.show(evt.getComponent(), evt.getX(), evt.getY());
//                    deportes.add(crearDeporte());
//                }
//                if (nodo.getUserObject().toString().equals("Q5")) {
//                    Pop_Torneos.show(evt.getComponent(), evt.getX(), evt.getY());
//                    deportes.add(crearDeporte());
//                

        if (evt.isMetaDown()) {
            int row = jtree_Torneos.getClosestRowForLocation(evt.getX(), evt.getY());
            jtree_Torneos.setSelectionRow(row);
            Object v1 = jtree_Torneos.getSelectionPath().getLastPathComponent();
            nodo_sel = (DefaultMutableTreeNode) v1;
            
            if (nodo_sel.getUserObject() instanceof Deportes) {
                Pop_Deportes.show(evt.getComponent(), evt.getX(), evt.getX());
            } else if (nodo_sel.getUserObject() instanceof Torneos){
                Pop_Torneos.show(evt.getComponent(), evt.getX(), evt.getX());
            }
            else {
                jPopupInicial.show(evt.getComponent(), evt.getX(), evt.getX());
            }
        }
    }//GEN-LAST:event_jtree_TorneosMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        crearDeporte();
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        deportes.add(crearDeporte());
        LlenarArbol();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
        if (evt.isMetaDown()) {
            System.out.println("pero1");
            int row = jtree_Torneos.getClosestRowForLocation(evt.getX(), evt.getY());
            jtree_Torneos.setSelectionRow(row);
            Object v1 = jtree_Torneos.getSelectionPath().getLastPathComponent();
            Torneos torneoSelecc = new Torneos();
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) v1;
        }
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public Deportes crearDeporte() {
        String nombre = JOptionPane.showInputDialog("Ingrese el Nombre");
        Deportes dep = new Deportes(nombre, new ArrayList<>());

        return dep;
    }

    public void LlenarArbol() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Torneos");
        DefaultTreeModel model = (DefaultTreeModel) jtree_Torneos.getModel();
        model.setRoot(root);

        for (int i = 1; i <= 5; i++) {
            if (i != 3) {
                String val = "Q" + Integer.toString(i);
                root.add(new DefaultMutableTreeNode(val));
            }
        }

        for (int i = 0; i < root.getChildCount(); i++) {
            DefaultMutableTreeNode nodo = (DefaultMutableTreeNode) root.getChildAt(i);
            String nombre = (String) nodo.getUserObject();

            for (Deportes deporte : deportes) {
                DefaultMutableTreeNode depor = new DefaultMutableTreeNode(deporte);

                nodo.add(depor);

                for (Torneos torneos : deporte.getTorneos()) {
                    if (torneos.getPeriodo().equals((String) nodo.getUserObject())) {
                        depor.add(new DefaultMutableTreeNode(torneos));
                    }
                }
            }
        }
        model.reload();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu Pop_Deportes;
    private javax.swing.JPopupMenu Pop_Torneos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupInicial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTree jtree_Torneos;
    // End of variables declaration//GEN-END:variables

    ArrayList<Deportes> deportes = new ArrayList();
    DefaultMutableTreeNode nodo_sel;
    Deportes dep_sel;
    Torneos tor_sel;
}
